In [382]:
from google.colab import drive
# This will prompt for authorization.
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [383]:
# import warnings
# warnings.filterwarnings('ignore')

In [384]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt

In [385]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [386]:
df = pd.read_csv("/content/drive/My Drive/ColabNotebooks/MachineLearning/SupportVectorMachine/BrainTumorClassification/data.csv",)

In [387]:
df.head()

Unnamed: 0  X53416  M83670  X90908  M97496  X90908.1  U37019  R48602  \
0           0      70     -81      25      10        22     113      36   
1           1     108     -30      -7      60         0      24       8   
2           2      75      -1       5      48         6      34      27   
3           3     871       4      14      78        -6      85      65   
4           4     -92     -34      14      19        11      -6      27   

   T96548  X64559  ...  H87456  R64130  H11125.1  U22055  L22524  M13699.1  \
0     163       9  ...      75       5        68     138      53        -4   
1     113      -3  ...     186       6        60      93     140        -3   
2      35      -1  ...     186     225        94      62      39       -14   
3     227      19  ...      77       6        78      30      87        -4   
4      -8       9  ...      87     303       204      81     105         9   

   X54489  T55008  M10065.2      y  
0     123       2        19  tumor  
1     271      -1       -51  tumor  
2     127       7       192  tumor  
3      59       3       367  tumor  
4     265      -2       126  tumor  

[5 rows x 7466 columns]

In [388]:
df.shape            #(rows, cols)

(36, 7466)

In [389]:
df.columns

Index(['Unnamed: 0', 'X53416', 'M83670', 'X90908', 'M97496', 'X90908.1',
       'U37019', 'R48602', 'T96548', 'X64559',
       ...
       'H87456', 'R64130', 'H11125.1', 'U22055', 'L22524', 'M13699.1',
       'X54489', 'T55008', 'M10065.2', 'y'],
      dtype='object', length=7466)

In [390]:
# get the list of column names
cols_to_drop = df.columns[0:7446] # slicing perform from 0 index to 7445 index

In [391]:
cols_to_drop

Index(['Unnamed: 0', 'X53416', 'M83670', 'X90908', 'M97496', 'X90908.1',
       'U37019', 'R48602', 'T96548', 'X64559',
       ...
       'R32511', 'X54942.1', 'X17668', 'Z48481', 'T60780', 'U33286', 'H50438',
       'L29254', 'M77349', 'R08183'],
      dtype='object', length=7446)

In [392]:
# drop the columns
df.drop(cols_to_drop, axis=1, inplace=True) #axis=1 argument to indicate that we want to drop columns

In [393]:
df.head()

X02530  L23808  M36821  D21262  T89991  M77836  H64555  M61832  J04765  \
0       1      27     137      96      -4     108       4     224      18   
1      17      62     206      74      -2     106      31     198      24   
2      61      73     196      77      -6     123       3      89      10   
3      20      70     119      28       4      51     155     154      36   
4      85      96     337      39      -4     122      -1     258       6   

   D14657  H87456  R64130  H11125.1  U22055  L22524  M13699.1  X54489  T55008  \
0      44      75       5        68     138      53        -4     123       2   
1     110     186       6        60      93     140        -3     271      -1   
2      98     186     225        94      62      39       -14     127       7   
3      54      77       6        78      30      87        -4      59       3   
4     142      87     303       204      81     105         9     265      -2   

   M10065.2      y  
0        19  tumor  
1       -51  tumor  
2       192  tumor  
3       367  tumor  
4       126  tumor

In [394]:
df.shape

(36, 20)

In [395]:
df.columns

Index(['X02530', 'L23808', 'M36821', 'D21262', 'T89991', 'M77836', 'H64555',
       'M61832', 'J04765', 'D14657', 'H87456', 'R64130', 'H11125.1', 'U22055',
       'L22524', 'M13699.1', 'X54489', 'T55008', 'M10065.2', 'y'],
      dtype='object')

#Change the columns name:

In [396]:
# create a dictionary that maps old column names to new column names
column_names = {
    'X02530':'x1', 
    'L23808':'x2', 
    'M36821':'x3', 
    'D21262':'x4', 
    'T89991':'x5', 
    'M77836':'x6', 
    'H64555':'x7',
    'M61832':'x8', 
    'J04765':'x9', 
    'D14657':'x10', 
    'H87456':'x11', 
    'R64130':'x12', 
    'H11125.1':'x13',
    'U22055':'x14',
    'L22524':'x15',
    'M13699.1':'x16',
    'X54489':'x17',
    'T55008':'x18',
    'M10065.2':'x19',
}

In [397]:
# use the rename() method to replace the column names
df.rename(columns=column_names, inplace=True)

In [398]:
df.columns

Index(['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11',
       'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'y'],
      dtype='object')

#Check unique value in single column

In [399]:
df['x1'].unique()

array([  1,  17,  61,  20,  85,  24,  22,  12,   6,   7,   2, 111,  42,
        21,   3,  68, 368,   8,   5,   4,  13,  15,  16,  10,   9])

# Check unique value in columns

In [400]:
# get the list of column names that we want to check
columns_to_check = ['x2', 'x3', 'x4', 'x5',
                    'x6', 'x7', 'x8', 'x9', 'x10',
                    'x11', 'x12', 'x13', 'x14', 'x15',
                    'x16', 'x17', 'x18', 'x19']

In [401]:
# loop through the columns and print the unique values
for col in columns_to_check:
    unique_values = df[col].unique()
    print(f"Unique values in {col}: {unique_values}")

Unique values in x2: [ 27  62  73  70  96  26  60  63  53  36  15 107  89 129  23  52 258  43
   0  24  16  -5  20   3  51  14   8   6  22   7  -4  58  19   2]
Unique values in x3: [137 206 196 119 337  -6 187  52  57  97  18 122 294 228  71 216  48 164
   9  26  56  51  40   6  13   8  20  70  17  33  35   4  72]
Unique values in x4: [ 96  74  77  28  39  30  24  12  61  55 141  37  68  26  43  64  31  94
  17  16   8  10   0   1  -9  19   3   5  -4  15   2  34]
Unique values in x5: [ -4  -2  -6   4  -5 -11 958  10   2  -1  -3   0   8 -25   7  -8 -14]
Unique values in x6: [108 106 123  51 122  54  67  74  63  85 147  99  93 155 150   9  10  23
  40   3  47   8  12  31  18  24  27   1  22   2]
Unique values in x7: [  4  31   3 155  -1  11  -4   9  15   0  17   5 619  13 142  36  -2 -13
 -21  -7  14 -17  10   1  -5 -12]
Unique values in x8: [224 198  89 154 258  13 112  12   6  70  80 151  56 254  92 146 229  71
  54  21  40  46  14  53  10  -3 -14  32  38  15  26  -2   9 -11  29]
Uniqu

# convert negative integer values to positive integer values for a column


In [402]:
df['x2'] = df['x2'].abs()

In [403]:
df['x2']

0      27
1      62
2      73
3      70
4      96
5      26
6      60
7      63
8      53
9      36
10     15
11    107
12     89
13    129
14     23
15     52
16    258
17     43
18      0
19     24
20     16
21      5
22     20
23      3
24     51
25     14
26      8
27      6
28     22
29      5
30     16
31      7
32      4
33     58
34     19
35      2
Name: x2, dtype: int64

# convert negative integer values to positive integer values for columns

In [404]:
# select the columns that we want to convert
columns_to_convert = [ 'x3', 'x4', 'x5', 'x7', 'x8', 'x9',
                      'x10','x11', 'x12', 'x13', 'x14', 
                      'x15','x16', 'x17', 'x18', 'x19']

In [405]:
# apply the abs function to the selected columns
df[columns_to_convert] = df[columns_to_convert].applymap(abs)  # applymap() method to apply the abs function to each element in the selected columns and replace the original values with their absolute values.

In [406]:
# select the columns that we want to convert
columns_to_check = [ 'x3', 'x4', 'x5', 'x7', 'x8', 'x9',
                      'x10','x11', 'x12', 'x13', 'x14', 
                      'x15','x16', 'x17', 'x18', 'x19']

In [407]:
# loop through the columns and print the unique values
for col in columns_to_check:
    unique_values = df[col].unique()
    print(f"Unique values in {col}: {unique_values}")

Unique values in x3: [137 206 196 119 337   6 187  52  57  97  18 122 294 228  71 216  48 164
   9  26  56  51  40  13   8  20  70  17  33  35   4  72]
Unique values in x4: [ 96  74  77  28  39  30  24  12  61  55 141  37  68  26  43  64  31  94
  17  16   8  10   0   1   9  19   3   5   4  15   2  34]
Unique values in x5: [  4   2   6   5  11 958  10   1   3   0   8  25   7  14]
Unique values in x7: [  4  31   3 155   1  11   9  15   0  17   5 619  13 142  36   2  21   7
  14  10  12]
Unique values in x8: [224 198  89 154 258  13 112  12   6  70  80 151  56 254  92 146 229  71
  54  21  40  46  14  53  10   3  32  38  15  26   2   9  11  29]
Unique values in x9: [ 18  24  10  36   6  83  26 248 100 118   7   1  94 114 122  15 109   3
  12   5   0   8  13  11  16]
Unique values in x10: [ 44 110  98  54 142   2  46  15  14  18  93 156 107  20  96 135   8   4
   3  21  11  13   0   7  19]
Unique values in x11: [ 75 186  77  87  51  64  84 115 686  66  53  20 191  58  10   1  24  17
   3 

In [408]:
df.isnull().sum()

x1     0
x2     0
x3     0
x4     0
x5     0
x6     0
x7     0
x8     0
x9     0
x10    0
x11    0
x12    0
x13    0
x14    0
x15    0
x16    0
x17    0
x18    0
x19    0
y      0
dtype: int64

In [409]:
df.duplicated().sum()

0

#Split data into dependent  and independent variables

In [410]:
# Split data into dependent  and independent variables
#X = df.iloc[:, :-1].values   # Independent variables
#y = df.iloc[:, -1].values    # Dependent variable  
#The iloc function is used to slice the DataFrame into the desired columns. 
#The : in the square brackets indicates that we want all rows of the dataset, and -1 indicates that we want all columns except the last one. 
#The .values function is used to convert the DataFrame to a numpy array, which is the format that scikit-learn (a popular machine learning library) uses.

#Label Encoding

In [411]:
from sklearn.preprocessing import LabelEncoder
# create a LabelEncoder object
encoder = LabelEncoder()
# fit the encoder to the data and transform the data
df['y'] = encoder.fit_transform(df['y'])
# print the encoded data
print(df['y'])

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
Name: y, dtype: int64


In [412]:
df['y'].unique()

array([1, 0])

In [413]:
X = df.drop('y',axis=1)
Y= df['y']

# Split data into training and testing sets

In [414]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
#can ensure that the same sequence of random numbers is generated each time you run the code, which helps you to obtain the same results every time.

In [415]:
from sklearn.svm import SVC
# Create an SVM classifier with a linear kernel
clf = SVC(kernel='linear')

In [416]:
# Train the classifier using the training data
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [417]:
y_train_predict = clf.predict(X_train)

In [418]:
y_train_predict.shape

(25,)

In [419]:
y_test_predict = clf.predict(X_test)

In [420]:
y_test_predict.shape

(11,)

In [421]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_test_predict)

array([[5, 0],
       [0, 6]])

In [422]:
df.columns

Index(['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11',
       'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'y'],
      dtype='object')

In [423]:
from sklearn.metrics import r2_score 
accuracy = r2_score(y_test, y_test_predict)

In [426]:
# Print the accuracy
print("Accuracy:", accuracy*100)

Accuracy: 100.0
